-- ARQUIVO & PRAZOS — schema inicial para Supabase
-- Execute no SQL Editor de um projeto NOVO do Supabase.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role text not null default 'user' check (role in ('admin','user','viewer')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.holidays (
  id uuid primary key default gen_random_uuid(),
  date date not null unique,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.cases (
  id uuid primary key default gen_random_uuid(),
  process_number text not null,
  case_name text not null,
  subject text not null,
  owner_id uuid not null references public.profiles(id),
  priority text not null default 'normal' check (priority in ('normal','high','urgent')),
  received_date date not null,
  deadline_date date not null,
  deadline_mode text not null check (deadline_mode in ('business','calendar','manual')),
  deadline_days integer,
  status text not null default 'active' check (status in ('active','done')),
  notes text,
  created_by uuid references auth.users(id) default auth.uid(),
  completed_by uuid references auth.users(id),
  completed_at date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.case_files (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references public.cases(id) on delete cascade,
  file_name text not null,
  storage_path text not null unique,
  size_bytes bigint,
  mime_type text,
  uploaded_by uuid references auth.users(id) default auth.uid(),
  created_at timestamptz not null default now()
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  case_id uuid references public.cases(id) on delete cascade,
  user_id uuid references auth.users(id),
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Atualiza updated_at automaticamente.
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;
drop trigger if exists trg_cases_updated_at on public.cases;
create trigger trg_cases_updated_at before update on public.cases
for each row execute function public.set_updated_at();

-- Cria perfil básico no primeiro cadastro do Auth.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email,'@',1)), 'user')
  on conflict (id) do nothing;
  return new;
end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Auditoria básica de criação/alteração/conclusão.
create or replace function public.audit_case_change()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if tg_op = 'INSERT' then
    insert into public.audit_log(case_id,user_id,action,details) values(new.id,auth.uid(),'created',jsonb_build_object('case_name',new.case_name));
    return new;
  elsif tg_op = 'UPDATE' then
    insert into public.audit_log(case_id,user_id,action,details) values(new.id,auth.uid(),case when old.status <> new.status then 'status_changed' else 'updated' end,jsonb_build_object('old_status',old.status,'new_status',new.status));
    return new;
  end if;
  return new;
end; $$;
drop trigger if exists trg_audit_cases on public.cases;
create trigger trg_audit_cases after insert or update on public.cases
for each row execute function public.audit_case_change();

-- RLS
alter table public.profiles enable row level security;
alter table public.holidays enable row level security;
alter table public.cases enable row level security;
alter table public.case_files enable row level security;
alter table public.audit_log enable row level security;

-- Usuários autenticados podem ler o banco coletivo.
create policy "profiles_read_authenticated" on public.profiles for select to authenticated using (true);
create policy "holidays_read_authenticated" on public.holidays for select to authenticated using (true);
create policy "cases_read_authenticated" on public.cases for select to authenticated using (true);
create policy "files_read_authenticated" on public.case_files for select to authenticated using (true);
create policy "audit_read_authenticated" on public.audit_log for select to authenticated using (true);

-- Servidores ativos podem criar e atualizar casos.
create policy "cases_insert_active" on public.cases for insert to authenticated
with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.active=true and p.role in ('admin','user')));
create policy "cases_update_active" on public.cases for update to authenticated
using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.active=true and p.role in ('admin','user')))
with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.active=true and p.role in ('admin','user')));

create policy "files_insert_active" on public.case_files for insert to authenticated
with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.active=true and p.role in ('admin','user')));

-- Administração de feriados e perfis apenas por admin.
create policy "holidays_admin_insert" on public.holidays for insert to authenticated with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin' and p.active=true));
create policy "holidays_admin_delete" on public.holidays for delete to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin' and p.active=true));
create policy "profiles_admin_update" on public.profiles for update to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin' and p.active=true));

-- Bucket privado de documentos.
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('case-files','case-files',false,10485760,array['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','image/png','image/jpeg'])
on conflict (id) do update set public=false,file_size_limit=10485760;

create policy "storage_read_authenticated" on storage.objects for select to authenticated using (bucket_id='case-files');
create policy "storage_insert_active" on storage.objects for insert to authenticated with check (
  bucket_id='case-files' and exists(select 1 from public.profiles p where p.id=auth.uid() and p.active=true and p.role in ('admin','user'))
);

-- IMPORTANTE: depois de criar o primeiro usuário no Auth, torne-o administrador:
-- update public.profiles set role='admin', full_name='SEU NOME' where id='UUID_DO_USUARIO';
